name: online-book-store-application
services:
  mysql_db_service:
    image: mysql
    restart: no
#    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=book_store_db
      - MYSQL_USER=root_1
      - MYSQL_PASSWORD=root_1
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysql_db_service
    image: online-book-store-image
    restart: no
    build: .
#    env_file: ./.env
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
        spring.datasource.url: jdbc:mysql://mysql_db_service:3306/book_store_db?user=root_1&password=root_1&serverTimezone=UTC
#        spring.datasource.username: root
#        spring.datasource.password: root
        spring.jpa.hibernate.ddl-auto: validate
        jwt.expiration: 36000000
        jwt.secret: very-very-very-long-secret-string
        JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
